package com.tetris.mab.nuke;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Hand-tuned default {@link NukeDesign}s. The DEFCON readiness maps
 * here are written explicitly (not generated by
 * {@link NukeReadinessScaler}) to match the Step-3 spec exactly.
 */
public final class NukeDesignFactory {

    private NukeDesignFactory() {}

    // ─────────────────────── Public factories ────────────────

    public static NukeDesign createDefaultPlaceholder() {
        Map<Integer, Integer> build = mapOf(5, 22, 4, 21, 3, 20, 2, 18, 1, 16);
        Map<Integer, List<Integer>> code = codes(
                5, List.of(1, 2, 1),
                4, List.of(1, 2, 1),
                3, List.of(1, 2, 1),
                2, List.of(1, 2),
                1, List.of(2));
        Map<Integer, Integer> launch  = mapOf(5, 5, 4, 4, 3, 4, 2, 3, 1, 3);
        Map<Integer, Integer> warning = mapOf(5, 5, 4, 4, 3, 4, 2, 3, 1, 3);

        return new NukeDesign(
                "placeholder_tactical", "Placeholder Tactical",
                NukeDoctrineType.PLACEHOLDER, NukeSizeCategory.TACTICAL,
                /*build*/20, /*blast*/2, /*rad*/1, /*disarm*/1, /*silo*/0,
                /*launchT*/4, /*warnT*/4, /*detection*/1,
                List.of(1, 2, 1),
                build, code, launch, warning,
                new GarbageProfile(2, 2, false, 0, 0, false),
                new DisarmProfile(1, 1.5, false, true),
                new SiloDamageProfile(0, false, false, false),
                null, null, null,
                FullClearThresholdProfile.defaults());
    }

    public static NukeDesign createDefaultCleanFusion() {
        Map<Integer, Integer> build = mapOf(5, 60, 4, 52, 3, 44, 2, 38, 1, 32);
        Map<Integer, List<Integer>> code = codes(
                5, List.of(4, 4, 4),
                4, List.of(4, 4, 3),
                3, List.of(4, 4),
                2, List.of(4, 3),
                1, List.of(4));
        Map<Integer, Integer> launch  = mapOf(5, 10, 4, 9, 3, 7, 2, 6, 1, 5);
        Map<Integer, Integer> warning = mapOf(5, 10, 4, 9, 3, 7, 2, 6, 1, 5);

        return new NukeDesign(
                "clean_fusion_strategic", "Clean Fusion Strategic",
                NukeDoctrineType.CLEAN_FUSION, NukeSizeCategory.STRATEGIC,
                44, 5, 1, 3, 1,
                7, 7, 3,
                List.of(4, 4),
                build, code, launch, warning,
                new GarbageProfile(5, 5, false, 0, 0, false),
                new DisarmProfile(3, 1.25, true, false),
                new SiloDamageProfile(1, true, false, false),
                null, null, null,
                FullClearThresholdProfile.defaults());
    }

    public static NukeDesign createDefaultDirtyBomb() {
        Map<Integer, Integer> build = mapOf(5, 25, 4, 24, 3, 22, 2, 20, 1, 18);
        Map<Integer, List<Integer>> code = codes(
                5, List.of(1, 3, 1),
                4, List.of(1, 3, 1),
                3, List.of(1, 3, 1),
                2, List.of(3, 1),
                1, List.of(3));
        Map<Integer, Integer> launch  = mapOf(5, 6, 4, 5, 3, 5, 2, 4, 1, 3);
        Map<Integer, Integer> warning = mapOf(5, 6, 4, 5, 3, 5, 2, 4, 1, 3);

        return new NukeDesign(
                "dirty_tactical", "Dirty Tactical",
                NukeDoctrineType.DIRTY_BOMB, NukeSizeCategory.TACTICAL,
                22, 2, 4, 1, 0,
                5, 5, 2,
                List.of(1, 3, 1),
                build, code, launch, warning,
                new GarbageProfile(2, 2, false, 0, 0, false),
                new DisarmProfile(1, 1.5, false, true),
                new SiloDamageProfile(0, false, false, false),
                null, null, null,
                FullClearThresholdProfile.defaults());
    }

    public static NukeDesign createDefaultConcreteBlaster() {
        Map<Integer, Integer> build = mapOf(5, 56, 4, 48, 3, 40, 2, 35, 1, 30);
        Map<Integer, List<Integer>> code = codes(
                5, List.of(2, 4, 2, 4),
                4, List.of(2, 4, 2),
                3, List.of(2, 4, 2),
                2, List.of(4, 2),
                1, List.of(4));
        Map<Integer, Integer> launch  = mapOf(5, 10, 4, 8, 3, 7, 2, 6, 1, 5);
        Map<Integer, Integer> warning = mapOf(5, 10, 4, 8, 3, 7, 2, 6, 1, 5);

        return new NukeDesign(
                "concrete_blaster", "Concrete Blaster",
                NukeDoctrineType.CONCRETE_BLASTER, NukeSizeCategory.STRATEGIC,
                40, 2, 1, 6, 5,
                7, 7, 3,
                List.of(2, 4, 2),
                build, code, launch, warning,
                new GarbageProfile(2, 2, false, 0, 0, true),
                new DisarmProfile(6, 0.9, true, false),
                new SiloDamageProfile(5, true, true, true),
                null, null, null,
                FullClearThresholdProfile.defaults());
    }

    public static NukeDesign createDefaultMirv() {
        Map<Integer, Integer> build = mapOf(5, 58, 4, 50, 3, 42, 2, 36, 1, 32);
        Map<Integer, List<Integer>> code = codes(
                5, List.of(3, 2, 3, 4),
                4, List.of(3, 2, 3),
                3, List.of(3, 2, 3),
                2, List.of(3, 4),
                1, List.of(4));
        Map<Integer, Integer> launch  = mapOf(5, 10, 4, 8, 3, 7, 2, 6, 1, 5);
        Map<Integer, Integer> warning = mapOf(5, 10, 4, 8, 3, 7, 2, 6, 1, 5);

        return new NukeDesign(
                "mirv_strategic", "MIRV Strategic",
                NukeDoctrineType.MIRV, NukeSizeCategory.STRATEGIC,
                42, 5, 2, 2, 1,
                7, 7, 4,
                List.of(3, 2, 3),
                build, code, launch, warning,
                new GarbageProfile(5, 1, true, 5, 2, false),
                new DisarmProfile(2, 1.25, false, false),
                new SiloDamageProfile(1, true, false, false),
                new MirvProfile(5, 1, 2),
                null, null,
                FullClearThresholdProfile.defaults());
    }

    public static NukeDesign createDefaultEmp() {
        Map<Integer, Integer> build = mapOf(5, 36, 4, 33, 3, 30, 2, 27, 1, 24);
        Map<Integer, List<Integer>> code = codes(
                5, List.of(1, 2, 2, 1),
                4, List.of(1, 2, 2, 1),
                3, List.of(1, 2, 2, 1),
                2, List.of(2, 2, 1),
                1, List.of(2, 2));
        Map<Integer, Integer> launch  = mapOf(5, 7, 4, 6, 3, 6, 2, 5, 1, 4);
        Map<Integer, Integer> warning = mapOf(5, 7, 4, 6, 3, 6, 2, 5, 1, 4);

        return new NukeDesign(
                "emp_payload", "EMP Payload",
                NukeDoctrineType.EMP_PAYLOAD, NukeSizeCategory.THEATER,
                30, 1, 2, 3, 2,
                6, 6, 2,
                List.of(1, 2, 2, 1),
                build, code, launch, warning,
                new GarbageProfile(1, 1, false, 0, 0, false),
                new DisarmProfile(3, 1.5, false, false),
                new SiloDamageProfile(2, true, false, true),
                null,
                new EmpProfile(5, 3, true),
                null,
                FullClearThresholdProfile.defaults());
    }

    public static NukeDesign createDefaultBunkerBuster() {
        Map<Integer, Integer> build = mapOf(5, 44, 4, 39, 3, 34, 2, 30, 1, 27);
        Map<Integer, List<Integer>> code = codes(
                5, List.of(3, 1, 3, 2),
                4, List.of(3, 1, 3),
                3, List.of(3, 1, 3),
                2, List.of(3, 3),
                1, List.of(3));
        Map<Integer, Integer> launch  = mapOf(5, 8, 4, 7, 3, 6, 2, 5, 1, 4);
        Map<Integer, Integer> warning = mapOf(5, 8, 4, 7, 3, 6, 2, 5, 1, 4);

        return new NukeDesign(
                "bunker_buster", "Bunker Buster",
                NukeDoctrineType.BUNKER_BUSTER, NukeSizeCategory.THEATER,
                34, 3, 0, 5, 5,
                6, 6, 3,
                List.of(3, 1, 3),
                build, code, launch, warning,
                new GarbageProfile(3, 3, false, 0, 0, true),
                new DisarmProfile(5, 1.0, true, false),
                new SiloDamageProfile(5, true, true, false),
                null, null, null,
                FullClearThresholdProfile.defaults());
    }

    public static NukeDesign createDefaultDoomsday() {
        Map<Integer, Integer> build = mapOf(5, 150, 4, 130, 3, 110, 2, 100, 1, 85);
        Map<Integer, List<Integer>> code = codes(
                5, List.of(4, 4, 4, 4, 4),
                4, List.of(4, 4, 4, 4),
                3, List.of(4, 4, 4),
                2, List.of(4, 4, 4),
                1, List.of(4, 4));
        Map<Integer, Integer> launch  = mapOf(5, 18, 4, 15, 3, 13, 2, 12, 1, 9);
        Map<Integer, Integer> warning = mapOf(5, 18, 4, 15, 3, 13, 2, 12, 1, 9);

        return new NukeDesign(
                "doomsday_device", "Doomsday Device",
                NukeDoctrineType.DOOMSDAY, NukeSizeCategory.DOOMSDAY_SCALE,
                100, 8, 3, 8, 8,
                12, 12, 5,
                List.of(4, 4, 4, 4),
                build, code, launch, warning,
                new GarbageProfile(8, 3, true, 4, 2, false),
                new DisarmProfile(8, 1.0, true, false),
                new SiloDamageProfile(8, true, true, true),
                null, null, null,
                FullClearThresholdProfile.defaults());
    }

    public static List<NukeDesign> createAllDefaults() {
        return List.of(
                createDefaultPlaceholder(),
                createDefaultCleanFusion(),
                createDefaultDirtyBomb(),
                createDefaultConcreteBlaster(),
                createDefaultMirv(),
                createDefaultEmp(),
                createDefaultBunkerBuster(),
                createDefaultDoomsday());
    }

    // ─────────────────────── Map literal helpers ─────────────

    private static Map<Integer, Integer> mapOf(int k1, int v1, int k2, int v2, int k3, int v3,
                                               int k4, int v4, int k5, int v5) {
        Map<Integer, Integer> m = new LinkedHashMap<>(8);
        m.put(k1, v1); m.put(k2, v2); m.put(k3, v3); m.put(k4, v4); m.put(k5, v5);
        return m;
    }

    private static Map<Integer, List<Integer>> codes(int k1, List<Integer> v1,
                                                     int k2, List<Integer> v2,
                                                     int k3, List<Integer> v3,
                                                     int k4, List<Integer> v4,
                                                     int k5, List<Integer> v5) {
        Map<Integer, List<Integer>> m = new LinkedHashMap<>(8);
        m.put(k1, v1); m.put(k2, v2); m.put(k3, v3); m.put(k4, v4); m.put(k5, v5);
        return m;
    }
}
