package com.tetris.mab.nuke;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Hand-tuned default {@link NukeDesign}s. The DEFCON readiness maps
 * here are written explicitly (not generated by
 * {@link NukeReadinessScaler}) so each preset gives the player a
 * distinct, predictable strategic identity.
 *
 * <p>The current preset ladder (MAB design):
 * <ol>
 *   <li>{@link #createDefaultPlaceholder()} — training payload.</li>
 *   <li>{@link #createDefaultTacticalBlast()} — light tactical.</li>
 *   <li>{@link #createDefaultDirtyPayload()} — dirty tactical.</li>
 *   <li>{@link #createDefaultEmp()} — EMP disruptor.</li>
 *   <li>{@link #createDefaultBunkerBuster()} — bunker buster.</li>
 *   <li>{@link #createDefaultConcreteBlaster()} — concrete blaster.</li>
 *   <li>{@link #createDefaultHeavyBlast()} — heavy strategic blast.</li>
 *   <li>{@link #createDefaultCleanFusion()} — clean fusion strategic.</li>
 *   <li>{@link #createDefaultSaltedPayload()} — salted payload.</li>
 *   <li>{@link #createDefaultDoomsday()} — doomsday.</li>
 * </ol>
 *
 * <p><b>Removed legacy presets:</b> the old {@code createDefaultMirv}
 * factory has been replaced by {@link #createDefaultHeavyBlast()}.
 * {@code createDefaultDirtyBomb()} is kept only as a deprecated alias
 * delegating to {@link #createDefaultDirtyPayload()}.
 */
public final class NukeDesignFactory {

    private NukeDesignFactory() {}

    // ─────────────────────── Public factories ────────────────

    public static NukeDesign createDefaultPlaceholder() {
        Map<Integer, Integer> build = mapOf(5, 22, 4, 21, 3, 20, 2, 18, 1, 16);
        Map<Integer, List<Integer>> code = codes(
                5, List.of(1, 2, 1),
                4, List.of(1, 2, 1),
                3, List.of(1, 2, 1),
                2, List.of(1, 2),
                1, List.of(2));
        Map<Integer, Integer> launch  = mapOf(5, 5, 4, 4, 3, 4, 2, 3, 1, 3);
        Map<Integer, Integer> impact  = mapOf(5, 5, 4, 4, 3, 4, 2, 3, 1, 3);

        return new NukeDesign(
                "placeholder_tactical", "Training Payload",
                NukeDoctrineType.PLACEHOLDER, NukeSizeCategory.TACTICAL,
                /*build*/20, /*blast*/2, /*rad*/1, /*disarm*/1, /*silo*/0, /*emp*/0,
                /*launchT*/4, /*impactDelay*/4,
                /*stability*/5, /*complexity*/2,
                List.of(1, 2, 1),
                build, code, launch, impact,
                new GarbageProfile(2, 2, false, 0, 0, false),
                new DisarmProfile(1, 1.5, false, true),
                new SiloDamageProfile(0, false, false, false),
                null,
                FullClearThresholdProfile.defaults());
    }

    public static NukeDesign createDefaultTacticalBlast() {
        Map<Integer, Integer> build = mapOf(5, 30, 4, 28, 3, 25, 2, 22, 1, 18);
        Map<Integer, List<Integer>> code = codes(
                5, List.of(1, 2, 1),
                4, List.of(1, 2, 1),
                3, List.of(1, 2),
                2, List.of(2),
                1, List.of(2));
        Map<Integer, Integer> launch = mapOf(5, 5, 4, 4, 3, 4, 2, 3, 1, 3);
        Map<Integer, Integer> impact = mapOf(5, 5, 4, 4, 3, 4, 2, 3, 1, 3);

        return new NukeDesign(
                "tactical_blast", "Light Tactical Blast",
                NukeDoctrineType.TACTICAL_BLAST, NukeSizeCategory.TACTICAL,
                25, 3, 1, 1, 0, 0,
                4, 4,
                6, 2,
                List.of(1, 2),
                build, code, launch, impact,
                new GarbageProfile(3, 3, false, 0, 0, false),
                new DisarmProfile(1, 1.5, false, true),
                new SiloDamageProfile(0, false, false, false),
                null,
                FullClearThresholdProfile.defaults());
    }

    public static NukeDesign createDefaultHeavyBlast() {
        Map<Integer, Integer> build = mapOf(5, 80, 4, 70, 3, 60, 2, 52, 1, 44);
        Map<Integer, List<Integer>> code = codes(
                5, List.of(3, 4, 3, 4),
                4, List.of(3, 4, 3),
                3, List.of(3, 4, 3),
                2, List.of(3, 4),
                1, List.of(4));
        Map<Integer, Integer> launch = mapOf(5, 10, 4, 9, 3, 8, 2, 7, 1, 6);
        Map<Integer, Integer> impact = mapOf(5, 10, 4, 9, 3, 8, 2, 7, 1, 6);

        return new NukeDesign(
                "heavy_blast", "Heavy Strategic Blast",
                NukeDoctrineType.HEAVY_BLAST, NukeSizeCategory.STRATEGIC,
                60, 7, 2, 3, 1, 0,
                8, 8,
                5, 6,
                List.of(3, 4, 3),
                build, code, launch, impact,
                new GarbageProfile(7, 5, false, 0, 0, false),
                new DisarmProfile(3, 1.25, true, false),
                new SiloDamageProfile(1, true, false, false),
                null,
                FullClearThresholdProfile.defaults());
    }

    public static NukeDesign createDefaultCleanFusion() {
        Map<Integer, Integer> build = mapOf(5, 60, 4, 52, 3, 44, 2, 38, 1, 32);
        Map<Integer, List<Integer>> code = codes(
                5, List.of(4, 4, 4),
                4, List.of(4, 4, 3),
                3, List.of(4, 4),
                2, List.of(4, 3),
                1, List.of(4));
        Map<Integer, Integer> launch = mapOf(5, 10, 4, 9, 3, 7, 2, 6, 1, 5);
        Map<Integer, Integer> impact = mapOf(5, 10, 4, 9, 3, 7, 2, 6, 1, 5);

        return new NukeDesign(
                "clean_fusion_strategic", "Clean Fusion Strategic",
                NukeDoctrineType.CLEAN_FUSION, NukeSizeCategory.STRATEGIC,
                44, 5, 1, 3, 1, 0,
                7, 7,
                7, 4,
                List.of(4, 4),
                build, code, launch, impact,
                new GarbageProfile(5, 5, false, 0, 0, false),
                new DisarmProfile(3, 1.25, true, false),
                new SiloDamageProfile(1, true, false, false),
                null,
                FullClearThresholdProfile.defaults());
    }

    public static NukeDesign createDefaultDirtyPayload() {
        Map<Integer, Integer> build = mapOf(5, 32, 4, 30, 3, 28, 2, 25, 1, 22);
        Map<Integer, List<Integer>> code = codes(
                5, List.of(1, 3, 1),
                4, List.of(1, 3, 1),
                3, List.of(1, 3, 1),
                2, List.of(3, 1),
                1, List.of(3));
        Map<Integer, Integer> launch = mapOf(5, 6, 4, 5, 3, 5, 2, 4, 1, 3);
        Map<Integer, Integer> impact = mapOf(5, 7, 4, 6, 3, 6, 2, 5, 1, 4);

        return new NukeDesign(
                "dirty_payload", "Dirty Tactical Payload",
                NukeDoctrineType.DIRTY_PAYLOAD, NukeSizeCategory.TACTICAL,
                28, 2, 4, 1, 0, 0,
                5, 6,
                4, 3,
                List.of(1, 3, 1),
                build, code, launch, impact,
                new GarbageProfile(6, 2, true, 3, 4, false),
                new DisarmProfile(1, 1.5, false, true),
                new SiloDamageProfile(0, false, false, false),
                null,
                FullClearThresholdProfile.defaults());
    }

    public static NukeDesign createDefaultSaltedPayload() {
        Map<Integer, Integer> build = mapOf(5, 60, 4, 55, 3, 50, 2, 45, 1, 40);
        Map<Integer, List<Integer>> code = codes(
                5, List.of(2, 3, 2, 3),
                4, List.of(2, 3, 2),
                3, List.of(2, 3, 2),
                2, List.of(2, 3),
                1, List.of(3));
        Map<Integer, Integer> launch = mapOf(5, 9, 4, 8, 3, 7, 2, 6, 1, 5);
        Map<Integer, Integer> impact = mapOf(5, 10, 4, 9, 3, 8, 2, 7, 1, 6);

        return new NukeDesign(
                "salted_payload", "Salted Payload",
                NukeDoctrineType.SALTED_PAYLOAD, NukeSizeCategory.STRATEGIC,
                50, 3, 6, 2, 1, 0,
                7, 8,
                4, 5,
                List.of(2, 3, 2),
                build, code, launch, impact,
                new GarbageProfile(8, 2, true, 4, 4, false),
                new DisarmProfile(2, 1.5, false, false),
                new SiloDamageProfile(1, true, false, false),
                null,
                FullClearThresholdProfile.defaults());
    }

    public static NukeDesign createDefaultConcreteBlaster() {
        Map<Integer, Integer> build = mapOf(5, 56, 4, 48, 3, 40, 2, 35, 1, 30);
        Map<Integer, List<Integer>> code = codes(
                5, List.of(2, 4, 2, 4),
                4, List.of(2, 4, 2),
                3, List.of(2, 4, 2),
                2, List.of(4, 2),
                1, List.of(4));
        Map<Integer, Integer> launch = mapOf(5, 10, 4, 8, 3, 7, 2, 6, 1, 5);
        Map<Integer, Integer> impact = mapOf(5, 10, 4, 8, 3, 7, 2, 6, 1, 5);

        return new NukeDesign(
                "concrete_blaster", "Concrete Blaster",
                NukeDoctrineType.CONCRETE_BLASTER, NukeSizeCategory.STRATEGIC,
                40, 2, 1, 6, 5, 0,
                7, 7,
                6, 4,
                List.of(2, 4, 2),
                build, code, launch, impact,
                new GarbageProfile(2, 2, false, 0, 0, true),
                new DisarmProfile(6, 0.9, true, false),
                new SiloDamageProfile(5, true, true, true),
                null,
                FullClearThresholdProfile.defaults());
    }

    public static NukeDesign createDefaultEmp() {
        Map<Integer, Integer> build = mapOf(5, 36, 4, 33, 3, 30, 2, 27, 1, 24);
        Map<Integer, List<Integer>> code = codes(
                5, List.of(1, 2, 2, 1),
                4, List.of(1, 2, 2, 1),
                3, List.of(1, 2, 2, 1),
                2, List.of(2, 2, 1),
                1, List.of(2, 2));
        Map<Integer, Integer> launch = mapOf(5, 7, 4, 6, 3, 6, 2, 5, 1, 4);
        Map<Integer, Integer> impact = mapOf(5, 7, 4, 6, 3, 6, 2, 5, 1, 4);

        return new NukeDesign(
                "emp_payload", "EMP Disruptor",
                NukeDoctrineType.EMP_PAYLOAD, NukeSizeCategory.THEATER,
                30, 1, 2, 3, 2, 6,
                6, 6,
                6, 4,
                List.of(1, 2, 2, 1),
                build, code, launch, impact,
                new GarbageProfile(1, 1, false, 0, 0, false),
                new DisarmProfile(3, 1.5, false, false),
                new SiloDamageProfile(2, true, false, true),
                EmpProfile.forDisruption(8, 2, 4),
                FullClearThresholdProfile.defaults());
    }

    public static NukeDesign createDefaultBunkerBuster() {
        Map<Integer, Integer> build = mapOf(5, 44, 4, 39, 3, 34, 2, 30, 1, 27);
        Map<Integer, List<Integer>> code = codes(
                5, List.of(3, 1, 3, 2),
                4, List.of(3, 1, 3),
                3, List.of(3, 1, 3),
                2, List.of(3, 3),
                1, List.of(3));
        Map<Integer, Integer> launch = mapOf(5, 8, 4, 7, 3, 6, 2, 5, 1, 4);
        Map<Integer, Integer> impact = mapOf(5, 8, 4, 7, 3, 6, 2, 5, 1, 4);

        return new NukeDesign(
                "bunker_buster", "Bunker Buster",
                NukeDoctrineType.BUNKER_BUSTER, NukeSizeCategory.THEATER,
                34, 3, 0, 5, 5, 0,
                6, 6,
                6, 4,
                List.of(3, 1, 3),
                build, code, launch, impact,
                new GarbageProfile(3, 3, false, 0, 0, true),
                new DisarmProfile(5, 1.0, true, false),
                new SiloDamageProfile(5, true, true, false),
                null,
                FullClearThresholdProfile.defaults());
    }

    public static NukeDesign createDefaultDoomsday() {
        Map<Integer, Integer> build = mapOf(5, 180, 4, 160, 3, 140, 2, 125, 1, 110);
        Map<Integer, List<Integer>> code = codes(
                5, List.of(4, 4, 4, 4, 4),
                4, List.of(4, 4, 4, 4),
                3, List.of(4, 4, 4),
                2, List.of(4, 4, 4),
                1, List.of(4, 4));
        Map<Integer, Integer> launch = mapOf(5, 18, 4, 15, 3, 13, 2, 12, 1, 9);
        Map<Integer, Integer> impact = mapOf(5, 18, 4, 15, 3, 13, 2, 12, 1, 9);

        return new NukeDesign(
                "doomsday_device", "Doomsday Device",
                NukeDoctrineType.DOOMSDAY, NukeSizeCategory.DOOMSDAY_SCALE,
                140, 9, 5, 8, 8, 4,
                12, 12,
                3, 9,
                List.of(4, 4, 4, 4),
                build, code, launch, impact,
                new GarbageProfile(10, 4, true, 4, 5, false),
                new DisarmProfile(8, 1.0, true, false),
                new SiloDamageProfile(8, true, true, true),
                EmpProfile.forDisruption(6, 1, 3),
                FullClearThresholdProfile.defaults());
    }

    /** @deprecated Replaced by {@link #createDefaultDirtyPayload()}. */
    @Deprecated
    public static NukeDesign createDefaultDirtyBomb() {
        return createDefaultDirtyPayload();
    }

    /**
     * @deprecated MIRV has been removed from the MAB doctrine model.
     * Old callers receive a heavy single-payload blast instead.
     */
    @Deprecated
    public static NukeDesign createDefaultMirv() {
        return createDefaultHeavyBlast();
    }

    public static List<NukeDesign> createAllDefaults() {
        return List.of(
                createDefaultPlaceholder(),
                createDefaultTacticalBlast(),
                createDefaultDirtyPayload(),
                createDefaultEmp(),
                createDefaultBunkerBuster(),
                createDefaultConcreteBlaster(),
                createDefaultHeavyBlast(),
                createDefaultCleanFusion(),
                createDefaultSaltedPayload(),
                createDefaultDoomsday());
    }

    // ─────────────────────── Map literal helpers ─────────────

    private static Map<Integer, Integer> mapOf(int k1, int v1, int k2, int v2, int k3, int v3,
                                               int k4, int v4, int k5, int v5) {
        Map<Integer, Integer> m = new LinkedHashMap<>(8);
        m.put(k1, v1); m.put(k2, v2); m.put(k3, v3); m.put(k4, v4); m.put(k5, v5);
        return m;
    }

    private static Map<Integer, List<Integer>> codes(int k1, List<Integer> v1,
                                                     int k2, List<Integer> v2,
                                                     int k3, List<Integer> v3,
                                                     int k4, List<Integer> v4,
                                                     int k5, List<Integer> v5) {
        Map<Integer, List<Integer>> m = new LinkedHashMap<>(8);
        m.put(k1, v1); m.put(k2, v2); m.put(k3, v3); m.put(k4, v4); m.put(k5, v5);
        return m;
    }
}
